# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41353cf2536dc5944abc80202f07bf1b1902e8afeb9e7c7f2433e16bc2cbcbabaa63372bb637784547c17fba9c03a933552893ce4889f558c32d0b7d29150404

test:
  secret_key_base: 834be93789d46a126c018f59dfb7d48be4c3942bcbfb0a595b2418125dc1aff7ea6ef88c8ab071fa621911be7ba052dd8330946b1f754c72d7e25a152e95db15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
